[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_crowdfunding_dapp = "8GvNsA64Bme86iJ2DkAJkugcwrtHa2AyhnApAqorHMY5"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "Localnet"
#wallet = "/Users/rluevanos/.config/solana/id.json"
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
